### ISSUE TITLE
Error 404 on chrome store 

### ISSUE THREAD

**Issue by rohanrajput04** [stvhwrd/GitHunt-Dark#13]
The chrome and chromium extension page is not working, I recently switched my laptop, can't get it to install on my new browsers. 

Please find the attached broken link
https://chrome.google.com/webstore/detail/githunt-dark/eaholbmncablicmnmlpngnhhgpkfcjfa

**Comment by stvhwrd** [comment]
Thanks for letting me know!  Please try again, it should work now.

**Comment by rohanrajput04** [comment]
Thank you :)
