### ISSUE TITLE
Hi, can this have a search box to search for github repos?

### ISSUE THREAD

**Issue by cmal** [stvhwrd/GitHunt-Dark#3]
Hi! I use this githunt everyday, and like it very much to be my default chrome tab. 
I am wondering whether it can have a search box just like github's search box, to search for github repos, so that I will not need to open github.com again, to search for a repo by name?
Thank you!

**Comment by stvhwrd** [comment]
Hi!  Thanks for your interest.  I don't have any plans to implement a search box as it would introduce another level of complexity to this simple new tab page.

If you like, you could set your new tab page to [GitHub Trending](https://github.com/trending) which displays much of the same information as GitHunt Dark, and includes a search box.  You could use a userscript like [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark) to save your eyeballs 😎 from the white-burn of the default GitHub theme.

Cheers @cmal 🍻

**Comment by cmal** [comment]
Awesome ideas. Thanks @stvhwrd .
